backend:
  name: github
  repo: neph-io/neph-io-web
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    format: "frontmatter"
    extension: "md"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Vignette", name: "thumbnail", widget: "image" }
      - { label: "Thumb Visible", name: "thumbpage", widget: "boolean", default: true }
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }


  - name: "projects"
    label: "Projets"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    format: "frontmatter"
    extension: "md"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Vignette", name: "thumbnail", widget: "image" }
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }


  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    format: "frontmatter"
    extension: "md"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image (URL ou upload)", name: "image", widget: "image" }
      - { label: "Légende", name: "caption", widget: "string" }